### ISSUE TITLE
Removing Escape Bytes from Communication Protocol

### ISSUE THREAD

**Issue by nikitaroz** [OSURoboticsClub/Rover2017#7]
@NickAmes it does not seem that the communication protocol actually has to have an escape byte because the size of the packet is always known. That is, a program can determine that a special byte within a packet is only data based on the expected size of the packet. If anything, the escape byte adds extra complexity and does not contain any new information. What are your thoughts on removing it from the specification?

**Comment by NickAmes** [comment]
We don't always know how large a packet will be, since packets like Callsign and Debugging Info can be different lengths. Although the length of the data is encoded in a field within the packet, this would require the packet layer recognize the packet type, inspect the interior of the packet, and take that into account. This process becomes more complicated if we ever want to use multiple variable-length fields, or more than one variable length fields in each packet. Also, even constant-length packets require the packet layer to know the length of every packet type.

Having special characters be escaped provides an additional advantage by allowing the start/end bytes to unconditionally synchronize packet parsing. If the connection is disrupted, the receiver will see the unescaped start/end byte and be able to get back on track immediately. (In fact, without this, the receiver might never get back on track.)

Actually, given the possibility for packet corruption due to the connection dropping out, I think we should add a checksum. I happen to have some working code from a past project that should work great.

**Comment by NickAmes** [comment]
Is the send/receive code for the software written yet? If not, do you want me to just write it? I think we're behind schedule for getting communication between the software and miniboard working. I'll be in Corvallis and available from the 28th onward if you'd like to meet up.

**Comment by nikitaroz** [comment]
I think it's safest to check the packet length before deserializing data anyway. And it would eliminate much of a need to implement a checksum because the possibility of creating an incorrect packet with a valid combination of start, type, and end bytes is highly unlikely. With regards to packets that have different sizes, the solution I kept seeing in other protocols is to encode the size of the packet right at the start.
In the case of a connection loss, the probability of encountering an end byte, a start byte, and a valid command byte that is actually data is exceedingly small ~1 / ( 256 * 256 * 20). If the size of the packet does not match, then the program discards the data and waits for the next sequence. 
I recently realized that the commgen.c file that I was originally planning on using would not work well on for the base software, so I'm currently working on writing some new communication code for the base station. I will let you know if I need any help with it.

**Comment by nikitaroz** [comment]
I just realized, if we put the size of the packet at the start of every packet, that would be a good checksum, be pretty easy to implement without much type checking, and remove the need for escape bytes. Could that be the better solution?

**Comment by NickAmes** [comment]
How about this:
  <start byte (0x01)>, \<length byte>, <2-byte CRC>, \<command byte>, [0 or more data bytes]
If we're going to the trouble of checking the length, let's use a real checksum that can catch errors in the packet data.

Here's the code for the CRC. The ```packet``` argument is the packet body (the command byte and data). If it matches the CRC in the packet, the packet is valid.
```
uint16_t calc_crc(uint8_t *packet, int packet_length){
	uint16_t remainder = 0xFFFF;
	
	for (int i = 0; i < packet_length; i++){
		remainder ^= packet[i] << 8;
		for (int bit = 8; bit > 0; bit--){
			if (remainder & 0x8000){
				remainder = (remainder << 1) ^ 0x1021;
			} else {
				remainder = (remainder << 1);
			}
		}
	}
	return remainder;
}
```

**Comment by nikitaroz** [comment]
That's a good idea. I think that would work. Where do we stand on the escape byte? It seems that having the size and checksum would be more than enough information to unambiguously determine the boundaries of a packet. And that would mean that the length byte is a simple lookup.
Also, minor thing, what do you think about having the checksum at the end of the packet? Might be a better place for it.

**Comment by NickAmes** [comment]
There would be no escape or end bytes in this new protocol, just a start byte. I like having the start byte, length, and CRC at the front since it partitions the packet into a header and body, rather than header-body-footer.

**Comment by nikitaroz** [comment]
Sounds good. I updated the specification  here #8 to comply with the new protocol. Please make any changes as needed.
